name: CI Integration

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Print Default Path
      run: pwd 
      
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image (dsail/dsail-server)
      with:
          image: dsail/dsail-server
          tags: v1, latest
          Dockerfile : /home/runner/work/D-SAIL/D-SAIL/federated_learning/server/Dockerfile
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
